# Generated by Django 5.1.2 on 2024-11-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100)),
                ('execution_time', models.CharField(max_length=20)),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('glutenfree', models.BooleanField(default=False)),
                ('lactosefree', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructions', models.TextField(blank=True)),
                ('ingredients', models.TextField(blank=True)),
            ],
        ),
    ]
